# Generated by Django 2.2.3 on 2019-07-24 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('p1', models.CharField(max_length=10)),
                ('p2', models.CharField(max_length=10)),
                ('p3', models.CharField(max_length=10)),
                ('p4', models.CharField(max_length=10)),
                ('p5', models.CharField(max_length=10)),
                ('p6', models.CharField(max_length=10)),
                ('p7', models.CharField(max_length=10)),
                ('p8', models.CharField(max_length=10)),
                ('p9', models.CharField(max_length=10)),
                ('p10', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('code', models.CharField(max_length=6)),
                ('p1', models.CharField(max_length=10)),
                ('p2', models.CharField(max_length=10)),
                ('p3', models.CharField(max_length=10)),
                ('p4', models.CharField(max_length=10)),
                ('p5', models.CharField(max_length=10)),
                ('p6', models.CharField(max_length=10)),
                ('p7', models.CharField(max_length=10)),
                ('p8', models.CharField(max_length=10)),
                ('p9', models.CharField(max_length=10)),
                ('p10', models.CharField(max_length=10)),
            ],
        ),
    ]
