# Generated by Django 2.2.3 on 2019-07-24 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='score',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='guest',
            name='b1',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='guest',
            name='b10',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='guest',
            name='b2',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='guest',
            name='b3',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='guest',
            name='b4',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='guest',
            name='b5',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='guest',
            name='b6',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='guest',
            name='b7',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='guest',
            name='b8',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='guest',
            name='b9',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='p1',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='p10',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='p2',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='p3',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='p4',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='p5',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='p6',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='p7',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='p8',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='p9',
            field=models.IntegerField(default=0),
        ),
    ]
