# Generated by Django 2.2.3 on 2019-07-24 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_auto_20190724_2150'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='p_num',
            field=models.IntegerField(default=0),
        ),
    ]
