# Generated by Django 2.2.3 on 2019-07-24 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_user_p_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='b1',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='guest',
            name='b10',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='guest',
            name='b2',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='guest',
            name='b3',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='guest',
            name='b4',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='guest',
            name='b5',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='guest',
            name='b6',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='guest',
            name='b7',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='guest',
            name='b8',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='guest',
            name='b9',
            field=models.IntegerField(default=0),
        ),
    ]
